name = Full Width Sidebars
description = Layout for basic pages with full-width wrapper and sidebars (no mid-content highlight bars)
template = full-width-sidebars

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/full-width-sidebars/full-width-sidebars.layout.css
